services:
  mlbserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlbserver
    environment:
      - TZ=America/Bogota
      - account_username=${ACCOUNT_USERNAME}
      - account_password=${ACCOUNT_PASSWORD}
      #- fav_teams=AZ,BAL
      #- http_root=/mlbserver
      #- debug=false
      #- multiview_path=
      #- ffmpeg_path=
      #- ffmpeg_encoder=
      #- page_username=
      #- page_password=
      #- content_protect=
      #- gamechanger_delay=0
      #- PUID=1000
      #- PGID=1000
    ports:
      - 9999:9999
    volumes:
      - mlb_data:/mlbserver/data_directory

volumes:
  mlb_data: